export const INCREMENT ='INCREMENT';
export const DECREMENT ='DECREMENT';
export const ADD_INCREMENT ='ADD_INCREMENT';
export const SUB_DECREMENT ='SUB_DECREMENT';
export const STORE_RESULT ='STORE_RESULT';
export const DELETE_RESULT ='DELETE_RESULT';
